//! `Http402Gate` — a Pingora [`ProxyHttp`] that runs the framework-agnostic
//! [`PaymentGate`] and then proxies **natively**:
//!
//! - metered / forwarded traffic → the endpoint's real upstream, reusing
//!   [`prepare_upstream`] for URL rewrite, header forwarding/stripping and auth
//!   injection (the exact same path axum's `forward_request` uses);
//! - control-plane paths (`/__402/*`, `/openapi.json`, `/.well-known/*`, `/`) →
//!   an internal axum service (`control_plane` address) that still serves them.
//!
//! This is the production data plane: Pingora fronts everything, axum is demoted
//! to an internal control-plane upstream.
//!
//! ## Deferred (documented)
//! - **Body-signing auth**: request bodies stream to the upstream unbuffered, so
//!   auth schemes that digest the body (HMAC / `AccessToken` `body_digest`) can't
//!   be signed here — those requests are **refused with 501** in
//!   [`Http402Gate::plan_upstream`] (loud + logged) rather than silently forwarded
//!   with a signature computed over an empty body. Header / Bearer / OAuth2 /
//!   QueryParam auth, and HMAC that doesn't digest the body, all work. Lifting
//!   this needs request-body buffering before the upstream connect.
//! - **Response metering**: Delegated MPP sessions and x402 `upto` share the
//!   buffered response-metering path so usage is rated once and settlement is
//!   persisted before release.

use async_trait::async_trait;
use bytes::{Bytes, BytesMut};
use futures_util::StreamExt;
use http::{HeaderMap, HeaderName, HeaderValue, StatusCode, Uri};
use pay_core::PaymentState;
use pay_core::server::gate::{
    GateDecision, GateRequest, GateResponse, PaymentGate, ReceiptAnnotation, SessionForward,
    settle_delegated_session as settle_delegated_session_forward, settle_upto, settle_upto_metered,
};
use pay_core::server::metering::{self, UptoSettlementPlan};
use pay_core::server::proxy::{
    STRIP_HEADERS, UpstreamPlan, prepare_upstream, routing_signs_request_body,
};
use pay_kit::x402::server::VerifiedUptoOpen;
use pay_types::metering::ApiSpec;
use pingora::http::{RequestHeader, ResponseHeader};
use pingora::proxy::{ProxyHttp, Session};
use pingora::upstreams::peer::HttpPeer;

const BUFFERED_REQUEST_BODY_LIMIT: usize = 16 * 1024 * 1024;
const DEFAULT_RESPONSE_BODY_LIMIT: usize = 1024 * 1024;

/// Where a non-`Respond` request should be proxied.
enum Target {
    /// Real API upstream resolved from the endpoint spec via `prepare_upstream`.
    Api {
        addr: String,
        tls: bool,
        sni: String,
        host_header: String,
        path_and_query: String,
        /// Forwarded client headers (minus stripped) + injected auth headers.
        headers: Vec<(String, String)>,
    },
    /// Internal axum service that serves the control plane.
    ControlPlane,
}

/// Per-request state threaded across the Pingora lifecycle hooks.
pub struct Ctx {
    target: Option<Target>,
    receipt: Option<ReceiptAnnotation>,
    /// An x402 `upto` channel opened pre-serve, settled in `response_filter`
    /// (debit on success) or `logging` (refund when the upstream never
    /// responded). Taken when settled, so it's never double-settled.
    upto: Option<PendingUpto>,
    /// A delegated MPP session opened pre-serve. Responses are buffered and
    /// rated with the same usage pipeline as x402 `upto`, then the gateway
    /// signs and persists the cumulative voucher before returning the body.
    session: Option<SessionForward>,
    /// Captured at `request_filter` for the Payment Debugger exchange emitted
    /// in `logging` (the data plane is Pingora, so the old axum logging
    /// middleware never sees proxied traffic).
    log: Option<LogStart>,
    /// Inference telemetry scanner over the upstream response body. Only
    /// created when the host opted into in-flight tracking
    /// (`record_request_start` returned a log id) — otherwise the body
    /// filter is a no-op.
    observer: Option<crate::observer::StreamObserver>,
    /// Final inference telemetry collected by the buffered x402-upto path.
    /// Buffered response-body metering settles before writing headers, so the
    /// streaming body observer is not used for those requests.
    buffered_usage: Option<pay_core::InferenceUsage>,
    /// Payment receipt headers generated by the gate/proxy and written to the
    /// downstream response. Pingora's recorded response can omit headers added
    /// by filters, so keep these explicitly for PDB logging.
    logged_payment_headers: Vec<(HeaderName, HeaderValue)>,
}

struct PendingUpto {
    open: VerifiedUptoOpen,
    settle_amount: u64,
    settlement: Option<UptoSettlementPlan>,
}

/// Request-side facts captured up front for the PDB exchange.
struct LogStart {
    method: String,
    path: String,
    req_headers: Vec<(String, String)>,
    client_ip: String,
    start: std::time::Instant,
    /// In-flight tracking id from `PaymentState::record_request_start`.
    log_id: Option<u64>,
}

/// Pingora payment gate over [`PaymentGate`], parameterized over the host's
/// [`PaymentState`].
pub struct Http402Gate<S: PaymentState> {
    state: S,
    /// `host:port` of the internal axum service handling the control plane.
    control_plane: String,
}

impl<S: PaymentState> Http402Gate<S> {
    pub fn new(state: S, control_plane: impl Into<String>) -> Self {
        Self {
            state,
            control_plane: control_plane.into(),
        }
    }

    /// Resolve the API spec for a host — subdomain match, single-API fallback —
    /// the same resolution [`PaymentGate::evaluate`] uses.
    fn resolve_api<'a>(&'a self, host: &str) -> Option<&'a ApiSpec> {
        let apis = self.state.apis();
        let subdomain = host.split('.').next().unwrap_or("");
        apis.iter()
            .find(|a| a.subdomain == subdomain)
            .or_else(|| if apis.len() == 1 { apis.first() } else { None })
    }

    /// Plan the upstream for a Forward/Passthrough decision: control-plane → the
    /// internal axum service; otherwise resolve + `prepare_upstream`. Returns
    /// `Ok(true)` if a response was written here (respond-mode / not-found /
    /// upstream-prep error), `Ok(false)` to continue to `upstream_peer`.
    #[allow(clippy::too_many_arguments)]
    async fn plan_upstream(
        &self,
        ctx: &mut Ctx,
        path: &str,
        host: Option<&str>,
        method: &http::Method,
        uri: &Uri,
        headers: &http::HeaderMap,
        session: &mut Session,
        // Whether this request may be served by the internal control-plane axum.
        // Only `Passthrough` (free / discovery) requests qualify; a `Forward`
        // (verified payment) for a root (`path: ""`) endpoint must reach the real
        // upstream, else the client paid but axum re-checks the stripped auth and
        // returns a 402.
        control_plane_ok: bool,
    ) -> pingora::Result<bool> {
        if control_plane_ok && is_control_plane(path) {
            ctx.target = Some(Target::ControlPlane);
            return Ok(false);
        }
        let Some(api) = self.resolve_api(host.unwrap_or("")) else {
            let _ = session
                .respond_error_with_body(404, Bytes::from_static(b"{\"error\":\"not_found\"}"))
                .await;
            return Ok(true);
        };
        // The body is streamed unbuffered (see module docs), so we can't compute
        // a body-digest signature here. Refuse loudly rather than forward a
        // request signed over an empty body (which the upstream would reject with
        // an opaque 401/403). Header / Bearer / OAuth2 / QueryParam auth, and
        // HMAC that doesn't digest the body, are unaffected.
        if routing_signs_request_body(api, path) {
            tracing::error!(
                path,
                "refusing request: upstream auth signs the request body, which the pingora data \
                 plane does not support (body is streamed, not buffered)"
            );
            // On a `Forward` the x402 `exact` payment already settled on-chain
            // (the gate settles in verify), so this 501 must still carry the
            // PAYMENT-RESPONSE receipt — otherwise the client is charged with no
            // proof. Drain it (and refund any `upto` channel) onto the response.
            let mut resp = GateResponse::json(
                StatusCode::NOT_IMPLEMENTED,
                Bytes::from_static(
                    b"{\"error\":\"unsupported_auth\",\"message\":\"This endpoint's upstream \
                      auth signs the request body, which the gateway does not yet support.\"}",
                ),
            );
            resp.headers
                .extend(self.drain_payment_headers(ctx, false).await);
            write_gate_response(session, resp).await?;
            return Ok(true);
        }
        // No body-signing auth → an empty placeholder body is safe for prep.
        match prepare_upstream(api, method, uri, headers, &[]).await {
            Ok(UpstreamPlan::Forward(prepared)) => {
                ctx.target = Some(target_from_prepared(prepared));
                Ok(false)
            }
            Ok(UpstreamPlan::Respond(resp)) => {
                self.finish_inline(session, ctx, resp).await?;
                Ok(true)
            }
            // Upstream-prep failure (bad URL, OAuth2 token fetch, body-prep): the
            // request ends here too, so run the same post-payment bookkeeping. An
            // x402 `exact` payment already settled on-chain before `Forward`, so
            // the client must still get its PAYMENT-RESPONSE receipt; any `upto`
            // channel is refunded since the resource was never served.
            Err(resp) => {
                self.finish_inline(session, ctx, resp).await?;
                Ok(true)
            }
        }
    }

    /// Finish a request that ends in `plan_upstream` (respond-mode response or an
    /// upstream-prep error) — `response_filter` never runs for these. Settle or
    /// refund any x402 `upto` channel (refund when the resource wasn't served)
    /// and attach the verified-payment receipt, then write the response.
    ///
    /// Draining `ctx.receipt` here matters on the error path: an x402 `exact`
    /// payment settles on-chain before the gate returns `Forward`, so a client
    /// that then hits an upstream-prep failure must still receive its
    /// PAYMENT-RESPONSE header to prove the charge (mirrors the axum gate, which
    /// appends receipt headers regardless of handler outcome).
    async fn finish_inline(
        &self,
        session: &mut Session,
        ctx: &mut Ctx,
        resp: axum::response::Response,
    ) -> pingora::Result<()> {
        let served_ok = resp.status().is_success();
        let extra = self.drain_payment_headers(ctx, served_ok).await;
        write_axum_response(session, resp, extra).await
    }

    /// Settle/refund pending payment side-effects and collect the headers that
    /// must ride the response: refund an open `upto` channel and surface the
    /// x402 `exact` `PAYMENT-RESPONSE` receipt. Used by every terminal path that
    /// `response_filter` doesn't reach (respond-mode, the body-signing 501
    /// refusal, and connect/proxy failures) so a settled payment always returns
    /// its proof. `served_ok` decides debit vs full refund for `upto`.
    async fn drain_payment_headers(
        &self,
        ctx: &mut Ctx,
        served_ok: bool,
    ) -> Vec<(HeaderName, HeaderValue)> {
        self.drain_payment_headers_with_response(ctx, served_ok, &HeaderMap::new(), None)
            .await
    }

    async fn drain_payment_headers_with_response(
        &self,
        ctx: &mut Ctx,
        served_ok: bool,
        response_headers: &HeaderMap,
        response_body: Option<&[u8]>,
    ) -> Vec<(HeaderName, HeaderValue)> {
        let mut extra: Vec<(HeaderName, HeaderValue)> = Vec::new();
        if !served_ok {
            // Dropping the forwarded session drops its capacity lease. Keep
            // this in the shared terminal-path drain so request buffering,
            // upstream setup/send, response buffering, and proxy failures all
            // release immediately.
            ctx.session.take();
        }
        if let Some(pending) = ctx.upto.take()
            && let Some((n, v)) = self
                .settle_pending_upto(pending, served_ok, response_headers, response_body)
                .await
        {
            extra.push((n, v));
        }
        if let Some(receipt) = ctx.receipt.take() {
            extra.extend(receipt.headers);
            if let Some(reference) = &receipt.reference {
                tracing::Span::current().record("tx_sig", reference.as_str());
            }
        }
        ctx.logged_payment_headers.extend(extra.iter().cloned());
        extra
    }

    async fn settle_pending_upto(
        &self,
        pending: PendingUpto,
        served_ok: bool,
        response_headers: &HeaderMap,
        response_body: Option<&[u8]>,
    ) -> Option<(HeaderName, HeaderValue)> {
        match pending.settlement {
            Some(plan) => {
                settle_upto_metered(
                    &self.state,
                    pending.open,
                    plan,
                    served_ok,
                    response_headers,
                    response_body,
                )
                .await
            }
            None => settle_upto(&self.state, pending.open, pending.settle_amount, served_ok).await,
        }
    }

    #[allow(clippy::too_many_arguments)]
    async fn forward_response_metered_buffered(
        &self,
        session: &mut Session,
        ctx: &mut Ctx,
        path: &str,
        host: Option<&str>,
        method: &http::Method,
        uri: &Uri,
        headers: &http::HeaderMap,
    ) -> pingora::Result<bool> {
        let Some(api) = self.resolve_api(host.unwrap_or("")) else {
            let extra = self.drain_payment_headers(ctx, false).await;
            write_buffered_response(
                session,
                StatusCode::NOT_FOUND,
                HeaderMap::new(),
                Bytes::from_static(b"{\"error\":\"not_found\"}"),
                extra,
            )
            .await?;
            return Ok(true);
        };

        let body = match read_downstream_body(session, BUFFERED_REQUEST_BODY_LIMIT).await {
            Ok(body) => body,
            Err(e) => {
                tracing::warn!(error = %e, "failed to buffer response-metered request body");
                let extra = self.drain_payment_headers(ctx, false).await;
                write_buffered_response(
                    session,
                    StatusCode::PAYLOAD_TOO_LARGE,
                    HeaderMap::new(),
                    Bytes::from_static(b"{\"error\":\"request_body_too_large\"}"),
                    extra,
                )
                .await?;
                return Ok(true);
            }
        };

        let prepared = match prepare_upstream(api, method, uri, headers, body.as_ref()).await {
            Ok(UpstreamPlan::Respond(resp)) => {
                self.finish_buffered_axum_response(session, ctx, resp)
                    .await?;
                return Ok(true);
            }
            Ok(UpstreamPlan::Forward(prepared)) => prepared,
            Err(resp) => {
                self.finish_buffered_axum_response(session, ctx, resp)
                    .await?;
                return Ok(true);
            }
        };

        let response_limit = ctx
            .upto
            .as_ref()
            .and_then(|pending| pending.settlement.as_ref())
            .or_else(|| {
                ctx.session
                    .as_ref()
                    .and_then(|pending| pending.settlement.as_deref())
            })
            .map(|plan| metering::upto_response_body_limit(&plan.metering))
            .unwrap_or(DEFAULT_RESPONSE_BODY_LIMIT);

        let client = reqwest::Client::new();
        let mut upstream_req = client.request(
            reqwest::Method::from_bytes(method.as_str().as_bytes()).unwrap(),
            prepared.url.clone(),
        );
        for (name, value) in buffered_upstream_headers(&prepared.headers) {
            upstream_req = upstream_req.header(name.as_str(), value);
        }
        if !body.is_empty() {
            upstream_req = upstream_req.body(body.to_vec());
        } else if matches!(method.as_str(), "POST" | "PUT" | "PATCH") {
            upstream_req = upstream_req.header("content-length", "0");
        }

        let upstream = match upstream_req.send().await {
            Ok(resp) => resp,
            Err(e) => {
                tracing::error!(error = %e, upstream = %prepared.url, "buffered upstream request failed");
                let extra = self.drain_payment_headers(ctx, false).await;
                write_buffered_response(
                    session,
                    StatusCode::BAD_GATEWAY,
                    HeaderMap::new(),
                    Bytes::from_static(b"{\"error\":\"upstream_unavailable\"}"),
                    extra,
                )
                .await?;
                return Ok(true);
            }
        };

        let status = StatusCode::from_u16(upstream.status().as_u16())
            .unwrap_or(StatusCode::INTERNAL_SERVER_ERROR);
        let response_headers = filtered_response_headers(upstream.headers());
        let body = match collect_reqwest_body(upstream, response_limit).await {
            Ok(body) => body,
            Err(e) => {
                tracing::warn!(error = %e, "failed to buffer response-metered body");
                let extra = self.drain_payment_headers(ctx, false).await;
                write_buffered_response(
                    session,
                    StatusCode::BAD_GATEWAY,
                    HeaderMap::new(),
                    Bytes::from_static(b"{\"error\":\"response_metering_failed\"}"),
                    extra,
                )
                .await?;
                return Ok(true);
            }
        };

        self.observe_buffered_metered_response(ctx, &response_headers, &body);
        if status.is_success() {
            match self
                .settle_delegated_session(ctx, &response_headers, &body)
                .await
            {
                Ok(Some(receipt)) => ctx.receipt = Some(receipt),
                Ok(None) => {}
                Err(error) => {
                    tracing::error!(%error, "failed to settle delegated MPP session usage");
                    let extra = self.drain_payment_headers(ctx, false).await;
                    write_buffered_response(
                        session,
                        StatusCode::BAD_GATEWAY,
                        HeaderMap::new(),
                        Bytes::from_static(b"{\"error\":\"session_settlement_failed\"}"),
                        extra,
                    )
                    .await?;
                    return Ok(true);
                }
            }
        }
        let extra = self
            .drain_payment_headers_with_response(
                ctx,
                status.is_success(),
                &response_headers,
                Some(&body),
            )
            .await;
        write_buffered_response(session, status, response_headers, body, extra).await?;
        tracing::debug!(
            path,
            "served payment via buffered response-metered proxy path"
        );
        Ok(true)
    }

    fn observe_buffered_metered_response(&self, ctx: &mut Ctx, headers: &HeaderMap, body: &[u8]) {
        let Some(plan) = ctx
            .upto
            .as_mut()
            .and_then(|pending| pending.settlement.as_mut())
            .or_else(|| {
                ctx.session
                    .as_mut()
                    .and_then(|pending| pending.settlement.as_deref_mut())
            })
        else {
            return;
        };
        let request_start = ctx
            .log
            .as_ref()
            .map(|log| log.start)
            .unwrap_or_else(std::time::Instant::now);
        let mut observer = crate::observer::StreamObserver::new(is_streamed_response(headers));
        if !body.is_empty() {
            observer.on_chunk(body, request_start);
        }
        observer.finish();
        let usage = observer.usage;
        plan.inferred_usage = Some(usage.clone());
        if let Some(log_id) = ctx.log.as_ref().and_then(|log| log.log_id) {
            self.state.record_exchange_update(log_id, &usage);
        }
        ctx.buffered_usage = Some(usage);
    }

    async fn settle_delegated_session(
        &self,
        ctx: &mut Ctx,
        response_headers: &HeaderMap,
        response_body: &[u8],
    ) -> Result<Option<ReceiptAnnotation>, String> {
        let Some(pending) = ctx.session.take() else {
            return Ok(None);
        };
        settle_delegated_session_forward(pending, response_headers, Some(response_body)).await
    }

    async fn finish_buffered_axum_response(
        &self,
        session: &mut Session,
        ctx: &mut Ctx,
        resp: axum::response::Response,
    ) -> pingora::Result<()> {
        let status = resp.status();
        let headers = resp.headers().clone();
        let body = match axum::body::to_bytes(resp.into_body(), DEFAULT_RESPONSE_BODY_LIMIT).await {
            Ok(body) => body,
            Err(e) => {
                tracing::warn!(error = %e, "failed to buffer inline response for x402 upto");
                Bytes::new()
            }
        };
        if status.is_success() {
            match self.settle_delegated_session(ctx, &headers, &body).await {
                Ok(Some(receipt)) => ctx.receipt = Some(receipt),
                Ok(None) => {}
                Err(error) => {
                    tracing::error!(%error, "failed to settle delegated MPP session usage");
                    let extra = self.drain_payment_headers(ctx, false).await;
                    return write_buffered_response(
                        session,
                        StatusCode::BAD_GATEWAY,
                        HeaderMap::new(),
                        Bytes::from_static(b"{\"error\":\"session_settlement_failed\"}"),
                        extra,
                    )
                    .await;
                }
            }
        }
        let extra = self
            .drain_payment_headers_with_response(ctx, status.is_success(), &headers, Some(&body))
            .await;
        write_buffered_response(session, status, headers, body, extra).await
    }
}

#[async_trait]
impl<S: PaymentState> ProxyHttp for Http402Gate<S> {
    type CTX = Ctx;
    fn new_ctx(&self) -> Ctx {
        Ctx {
            target: None,
            receipt: None,
            upto: None,
            session: None,
            log: None,
            observer: None,
            buffered_usage: None,
            logged_payment_headers: Vec::new(),
        }
    }

    async fn request_filter(&self, session: &mut Session, ctx: &mut Ctx) -> pingora::Result<bool> {
        let rh = session.req_header();
        let method = rh.method.clone();
        let uri = rh.uri.clone();
        let headers = rh.headers.clone();

        let path = uri.path().trim_start_matches('/').to_string();
        let str_h = |n: &str| headers.get(n).and_then(|v| v.to_str().ok());
        let host = str_h("host").map(str::to_string);

        // Capture request-side facts for the PDB exchange emitted in `logging`.
        // Skip the control plane's own paths (`/__402/*`, `/openapi.json`,
        // `/.well-known/*`, `/`) so the debugger only shows real traffic —
        // e.g. the ephemeral `/.well-known/pay-skills.json` that the MCP
        // catalog tools poll must not show up as a failed OLLAMA request.
        if !is_control_plane(&path) {
            let client_ip = str_h("x-forwarded-for")
                .and_then(|v| v.split(',').next())
                .map(|s| s.trim().to_string())
                .or_else(|| host.clone())
                .unwrap_or_else(|| "unknown".to_string());
            let mpp_payment = str_h("authorization")
                .map(|a| a.len() >= 8 && a[..8].eq_ignore_ascii_case("payment "))
                .unwrap_or(false);
            let x402_payment = str_h(pay_kit::x402::PAYMENT_SIGNATURE_HEADER).is_some()
                || str_h(pay_kit::x402::X402_V1_PAYMENT_HEADER).is_some();
            let log_id = self.state.record_request_start(&pay_core::RequestStart {
                method: method.to_string(),
                path: format!("/{path}"),
                host: host.clone(),
                client_ip: client_ip.clone(),
                payment: mpp_payment || x402_payment,
            });
            ctx.log = Some(LogStart {
                method: method.to_string(),
                path: format!("/{path}"),
                req_headers: header_pairs(&headers),
                client_ip,
                start: std::time::Instant::now(),
                log_id,
            });
        }
        let accept = str_h("accept").map(str::to_string);
        let authorization = str_h("authorization").map(str::to_string);
        let content_length = str_h("content-length").and_then(|v| v.parse::<u64>().ok());
        let query = uri.query().map(str::to_string);
        let x402_payment = str_h(pay_kit::x402::PAYMENT_SIGNATURE_HEADER)
            .or_else(|| str_h(pay_kit::x402::X402_V1_PAYMENT_HEADER))
            .map(str::to_string);

        let gate_req = GateRequest {
            method: &method,
            path: &path,
            host: host.as_deref(),
            accept: accept.as_deref(),
            authorization: authorization.as_deref(),
            content_length,
            query: query.as_deref(),
            x402_payment: x402_payment.as_deref(),
        };

        let decision = PaymentGate::new(self.state.clone())
            .evaluate(&gate_req)
            .await;
        match decision {
            GateDecision::Respond(r) => {
                write_gate_response(session, r).await?;
                Ok(true)
            }
            GateDecision::Forward {
                session: session_forward,
                receipt,
                upto,
            } => {
                ctx.receipt = receipt;
                // x402 `upto`: the channel is open; hold it for post-response
                // settlement (response_filter on success, logging on failure).
                ctx.upto = upto.map(|u| {
                    let u = *u;
                    PendingUpto {
                        open: *u.open,
                        settle_amount: u.settle_amount,
                        settlement: u.settlement,
                    }
                });
                ctx.session = session_forward;
                // Delegated sessions always settle before releasing a
                // successful response, including fixed-price endpoints. x402
                // `upto` only needs this path when pricing consumes response
                // usage; its fixed-price path can settle in response_filter.
                let delegated_session = ctx
                    .session
                    .as_ref()
                    .and_then(|pending| pending.settlement.as_ref())
                    .is_some();
                let response_metered_upto = ctx
                    .upto
                    .as_ref()
                    .and_then(|pending| pending.settlement.as_ref())
                    .is_some_and(|plan| {
                        metering::upto_requires_response_body(
                            &plan.metering,
                            plan.variant_hint.as_deref(),
                        )
                    });
                if delegated_session || response_metered_upto {
                    return self
                        .forward_response_metered_buffered(
                            session,
                            ctx,
                            &path,
                            host.as_deref(),
                            &method,
                            &uri,
                            &headers,
                        )
                        .await;
                }
                // A verified payment must reach the real upstream — never the
                // control-plane axum (`control_plane_ok = false`), even for a
                // root (`path: ""`) endpoint.
                self.plan_upstream(
                    ctx,
                    &path,
                    host.as_deref(),
                    &method,
                    &uri,
                    &headers,
                    session,
                    false,
                )
                .await
            }
            GateDecision::Passthrough => {
                // Free / discovery requests may be served by the control plane.
                self.plan_upstream(
                    ctx,
                    &path,
                    host.as_deref(),
                    &method,
                    &uri,
                    &headers,
                    session,
                    true,
                )
                .await
            }
        }
    }

    async fn upstream_peer(
        &self,
        _session: &mut Session,
        ctx: &mut Ctx,
    ) -> pingora::Result<Box<HttpPeer>> {
        match &ctx.target {
            Some(Target::Api { addr, tls, sni, .. }) => {
                Ok(Box::new(HttpPeer::new(addr.clone(), *tls, sni.clone())))
            }
            Some(Target::ControlPlane) => Ok(Box::new(HttpPeer::new(
                self.control_plane.clone(),
                false,
                "localhost".to_string(),
            ))),
            None => Err(pingora::Error::explain(
                pingora::ErrorType::InternalError,
                "no upstream target planned",
            )),
        }
    }

    async fn upstream_request_filter(
        &self,
        _session: &mut Session,
        upstream_request: &mut RequestHeader,
        ctx: &mut Ctx,
    ) -> pingora::Result<()> {
        if let Some(Target::Api {
            host_header,
            path_and_query,
            headers,
            ..
        }) = &ctx.target
        {
            if let Ok(uri) = path_and_query.parse::<Uri>() {
                let _ = upstream_request.set_uri(uri);
            }
            for h in STRIP_HEADERS {
                upstream_request.remove_header(*h);
            }
            let _ = upstream_request.insert_header("host", host_header.clone());
            for (k, v) in headers {
                let _ = upstream_request.insert_header(k.clone(), v.clone());
            }
        }
        Ok(())
    }

    async fn response_filter(
        &self,
        _session: &mut Session,
        upstream_response: &mut ResponseHeader,
        ctx: &mut Ctx,
    ) -> pingora::Result<()> {
        if let Some(receipt) = &ctx.receipt {
            for (name, value) in &receipt.headers {
                // Pass the HeaderValue through unchanged (a receipt can carry
                // non-ASCII bytes that `to_str()` would blank).
                let _ = upstream_response.insert_header(name.clone(), value.clone());
                ctx.logged_payment_headers
                    .push((name.clone(), value.clone()));
            }
            if let Some(reference) = &receipt.reference {
                tracing::Span::current().record("tx_sig", reference.as_str());
            }
        }
        // Start the inference telemetry observer for hosts that opted into
        // in-flight tracking. Response-body-metered x402-upto requests never
        // reach this path because they are buffered before downstream headers
        // are written so the PAYMENT-RESPONSE receipt can be attached.
        let observe_inference = ctx.log.as_ref().is_some_and(|log| log.log_id.is_some());
        if observe_inference {
            ctx.observer = Some(crate::observer::StreamObserver::new(is_streamed_response(
                &upstream_response.headers,
            )));
        }

        // x402 `upto`: the upstream responded. Settle the channel now (debit
        // on a 2xx, refund otherwise) and attach the PAYMENT-RESPONSE receipt
        // before the response streams downstream. Response-body-metered upto
        // requests were handled by `forward_upto_buffered`, so this inline path
        // only covers fixed-amount plans.
        if let Some(pending) = ctx.upto.take() {
            let served_ok = upstream_response.status.is_success();
            if let Some((name, value)) = self
                .settle_pending_upto(pending, served_ok, &upstream_response.headers, None)
                .await
            {
                let _ = upstream_response.insert_header(name.clone(), value.clone());
                ctx.logged_payment_headers.push((name, value));
            }
        }
        Ok(())
    }

    /// Scan upstream body chunks for inference telemetry (model, token usage,
    /// TTFT) without buffering the stream. Emits throttled live updates while
    /// the response runs. No-op unless `response_filter` armed the observer.
    fn upstream_response_body_filter(
        &self,
        _session: &mut Session,
        body: &mut Option<bytes::Bytes>,
        end_of_stream: bool,
        ctx: &mut Ctx,
    ) -> pingora::Result<()> {
        let Some(observer) = ctx.observer.as_mut() else {
            return Ok(());
        };
        let Some(log) = ctx.log.as_ref() else {
            return Ok(());
        };
        let Some(log_id) = log.log_id else {
            return Ok(());
        };

        if let Some(chunk) = body.as_ref()
            && !chunk.is_empty()
        {
            observer.on_chunk(chunk, log.start);
        }
        if end_of_stream {
            observer.finish();
            self.state.record_exchange_update(log_id, &observer.usage);
        } else if observer.should_emit() {
            self.state.record_exchange_update(log_id, &observer.usage);
        }
        Ok(())
    }

    /// Emit the completed exchange to the Payment Debugger. Pingora is the data
    /// plane, so the old axum `logging_middleware` never sees proxied traffic —
    /// this is what keeps PDB populated. Fires for every request (short-circuit
    /// 402s included); control-plane paths were filtered out at capture time.
    async fn logging(&self, session: &mut Session, _e: Option<&pingora::Error>, ctx: &mut Ctx)
    where
        Self::CTX: Send + Sync,
    {
        // An x402 `upto` channel still held here means a terminal hook did not
        // drain it (for example, response_filter never ran because upstream
        // connect/response failed). Refund rather than stranding funds. A
        // successful response-body-metered channel is settled before headers
        // are written in `forward_upto_buffered`, so its receipt reaches the
        // client as a normal PAYMENT-RESPONSE header.
        let mut deferred_payment_headers = Vec::new();
        // Covers cancellation/disconnect paths that bypassed all explicit
        // drains. Dropping the session releases its capacity lease.
        ctx.session.take();
        if let Some(pending) = ctx.upto.take()
            && let Some(header) = self
                .settle_pending_upto(pending, false, &HeaderMap::new(), None)
                .await
        {
            deferred_payment_headers.push(header);
        }
        let Some(log) = ctx.log.take() else {
            return;
        };
        let (status, mut res_headers) = match session.response_written() {
            Some(resp) => (resp.status.as_u16(), header_pairs(&resp.headers)),
            None => (0, Vec::new()),
        };
        let logged_payment_headers = std::mem::take(&mut ctx.logged_payment_headers);
        res_headers.extend(header_pairs_from_owned(deferred_payment_headers));
        res_headers.extend(header_pairs_from_owned(logged_payment_headers));
        // Flush the observer if the body filter never saw end_of_stream
        // (upstream error / client disconnect) so partial telemetry survives.
        let usage = ctx.buffered_usage.take().or_else(|| {
            ctx.observer.take().map(|mut observer| {
                observer.finish();
                observer.usage
            })
        });
        self.state.record_exchange(pay_core::HttpExchange {
            method: log.method,
            path: log.path,
            status,
            ms: log.start.elapsed().as_millis() as u64,
            req_headers: log.req_headers,
            res_headers,
            client_ip: log.client_ip,
            log_id: log.log_id,
            usage,
        });
    }

    /// Don't log downstream disconnects as proxy errors — a client closing a
    /// long-lived stream (e.g. the PDB `/__402/pdb/logs/stream` SSE on a tab
    /// close/refresh) is benign, not a gateway failure.
    fn suppress_error_log(&self, _session: &Session, _ctx: &Ctx, e: &pingora::Error) -> bool {
        matches!(e.esource(), pingora::ErrorSource::Downstream)
    }

    /// Write the downstream error response when proxying fails. `response_filter`
    /// only runs on a real upstream response, so a connect/TLS failure (or any
    /// pre-response proxy error) skips it. Recover the pending payment
    /// side-effects here — refund an open `upto` channel and re-attach the x402
    /// `exact` receipt — so a client whose payment already settled on-chain
    /// still receives its PAYMENT-RESPONSE instead of a bare 502 (mirrors
    /// `finish_inline` and `response_filter`). Falls back to Pingora's canned
    /// error when there is no receipt to preserve.
    async fn fail_to_proxy(
        &self,
        session: &mut Session,
        e: &pingora::Error,
        ctx: &mut Ctx,
    ) -> pingora::proxy::FailToProxy
    where
        Self::CTX: Send + Sync,
    {
        let extra = self.drain_payment_headers(ctx, false).await;

        // Mirror Pingora's default downstream error-code derivation so behavior
        // is unchanged except for the preserved payment headers.
        let code = match e.etype() {
            pingora::ErrorType::HTTPStatus(code) => *code,
            _ => match e.esource() {
                pingora::ErrorSource::Upstream => 502,
                pingora::ErrorSource::Downstream => match e.etype() {
                    pingora::ErrorType::WriteError
                    | pingora::ErrorType::ReadError
                    | pingora::ErrorType::ConnectionClosed => 0, // conn already dead
                    _ => 400,
                },
                pingora::ErrorSource::Internal | pingora::ErrorSource::Unset => 500,
            },
        };

        if code > 0 {
            if extra.is_empty() {
                let _ = session.respond_error(code).await;
            } else {
                let body = Bytes::from_static(b"{\"error\":\"upstream_unavailable\"}");
                match ResponseHeader::build(code, None) {
                    Ok(mut resp) => {
                        for (n, v) in extra {
                            let _ = resp.insert_header(n, v);
                        }
                        let _ = resp.insert_header("content-type", "application/json");
                        let _ = resp.insert_header("content-length", body.len().to_string());
                        if session
                            .write_response_header(Box::new(resp), false)
                            .await
                            .is_ok()
                        {
                            let _ = session.write_response_body(Some(body), true).await;
                        }
                    }
                    Err(err) => {
                        tracing::error!(error = %err, "failed to build payment-preserving error response");
                        let _ = session.respond_error(code).await;
                    }
                }
            }
        }

        pingora::proxy::FailToProxy {
            error_code: code,
            can_reuse_downstream: false,
        }
    }
}

/// Collect an `http::HeaderMap` into `(name, value)` string pairs for PDB.
///
/// Uses lossy UTF-8 rather than `to_str()` — the latter rejects any non-visible-
/// ASCII byte, which would silently drop a `WWW-Authenticate` whose challenge
/// description carries a non-ASCII char (e.g. an em-dash). PDB's correlation
/// engine keys on that header, so dropping it means the flow never appears.
fn header_pairs(headers: &HeaderMap) -> Vec<(String, String)> {
    headers
        .iter()
        .map(|(k, v)| {
            (
                k.as_str().to_string(),
                String::from_utf8_lossy(v.as_bytes()).into_owned(),
            )
        })
        .collect()
}

fn header_pairs_from_owned(headers: Vec<(HeaderName, HeaderValue)>) -> Vec<(String, String)> {
    headers
        .into_iter()
        .map(|(k, v)| {
            (
                k.as_str().to_string(),
                String::from_utf8_lossy(v.as_bytes()).into_owned(),
            )
        })
        .collect()
}

fn is_control_plane(path: &str) -> bool {
    path.is_empty()
        || path.starts_with("__402/")
        || path == "openapi.json"
        || path.starts_with(".well-known/")
}

/// Split a prepared upstream request into a connectable [`Target::Api`].
fn target_from_prepared(prepared: pay_core::server::proxy::PreparedUpstreamRequest) -> Target {
    let url = prepared.url;
    let tls = url.scheme() == "https";
    let host = url.host_str().unwrap_or("").to_string();
    let port = url
        .port_or_known_default()
        .unwrap_or(if tls { 443 } else { 80 });
    let default_port = (tls && port == 443) || (!tls && port == 80);
    let host_header = if default_port {
        host.clone()
    } else {
        format!("{host}:{port}")
    };
    let path_and_query = match url.query() {
        Some(q) => format!("{}?{}", url.path(), q),
        None => url.path().to_string(),
    };
    Target::Api {
        addr: format!("{host}:{port}"),
        tls,
        sni: host,
        host_header,
        path_and_query,
        headers: prepared.headers,
    }
}

fn buffered_upstream_headers(headers: &[(String, String)]) -> Vec<(String, String)> {
    let mut out = Vec::with_capacity(headers.len() + 1);
    for (name, value) in headers {
        if name.eq_ignore_ascii_case("accept-encoding") {
            continue;
        }
        out.push((name.clone(), value.clone()));
    }
    out.push(("accept-encoding".to_string(), "identity".to_string()));
    out
}

async fn read_downstream_body(session: &mut Session, limit: usize) -> pingora::Result<Bytes> {
    let mut buf = BytesMut::new();
    while let Some(chunk) = session.read_request_body().await? {
        if buf.len().saturating_add(chunk.len()) > limit {
            return Err(pingora::Error::explain(
                pingora::ErrorType::HTTPStatus(413),
                "buffered request body too large",
            ));
        }
        buf.extend_from_slice(&chunk);
    }
    Ok(buf.freeze())
}

async fn collect_reqwest_body(response: reqwest::Response, limit: usize) -> anyhow::Result<Bytes> {
    if let Some(content_length) = response.content_length()
        && content_length as usize > limit
    {
        anyhow::bail!("response body exceeds configured limit");
    }

    let mut stream = response.bytes_stream();
    let mut buf = BytesMut::new();
    while let Some(chunk) = stream.next().await {
        let chunk = chunk?;
        if buf.len().saturating_add(chunk.len()) > limit {
            anyhow::bail!("response body exceeds configured limit");
        }
        buf.extend_from_slice(&chunk);
    }
    Ok(buf.freeze())
}

fn filtered_response_headers(headers: &reqwest::header::HeaderMap) -> HeaderMap {
    let mut out = HeaderMap::new();
    for (name, value) in headers {
        let name_lower = name.as_str();
        if matches!(name_lower, "content-length" | "transfer-encoding") {
            continue;
        }
        if let (Ok(n), Ok(v)) = (
            HeaderName::from_bytes(name.as_str().as_bytes()),
            HeaderValue::from_bytes(value.as_bytes()),
        ) {
            out.insert(n, v);
        }
    }
    out
}

fn is_streamed_response(headers: &HeaderMap) -> bool {
    headers
        .get("content-type")
        .and_then(|v| v.to_str().ok())
        .map(|ct| {
            let ct = ct.to_ascii_lowercase();
            ct.starts_with("text/event-stream") || ct.starts_with("application/x-ndjson")
        })
        .unwrap_or(false)
}

async fn write_buffered_response(
    session: &mut Session,
    status: StatusCode,
    headers: HeaderMap,
    body: Bytes,
    extra: Vec<(HeaderName, HeaderValue)>,
) -> pingora::Result<()> {
    let mut out = ResponseHeader::build(status.as_u16(), None)?;
    for (n, v) in headers {
        let Some(n) = n else {
            continue;
        };
        if n.as_str().eq_ignore_ascii_case("content-length") {
            continue;
        }
        out.append_header(n, v)?;
    }
    for (n, v) in extra {
        let _ = out.append_header(n, v);
    }
    out.insert_header("content-length", body.len().to_string())?;
    session.write_response_header(Box::new(out), false).await?;
    session.write_response_body(Some(body), true).await?;
    Ok(())
}

/// Write a gate-produced [`GateResponse`] (402 challenge, 404, receipt JSON, …)
/// directly to the downstream and stop. Duplicate `WWW-Authenticate` lines are
/// preserved via `append_header`.
async fn write_gate_response(session: &mut Session, r: GateResponse) -> pingora::Result<()> {
    // An unread request body breaks HTTP/1.1 keepalive on a short-circuit.
    let _ = session.drain_request_body().await;
    let mut resp = ResponseHeader::build(r.status.as_u16(), None)?;
    for (name, value) in &r.headers {
        // Pass the `http::HeaderValue` through unchanged. The previous
        // `value.to_str().unwrap_or("")` silently blanked any value `to_str()`
        // rejected — dropping the `WWW-Authenticate` challenge on the floor.
        resp.append_header(name.clone(), value.clone())?;
    }
    resp.insert_header("content-length", r.body.len().to_string())?;
    session.write_response_header(Box::new(resp), false).await?;
    session.write_response_body(Some(r.body), true).await?;
    Ok(())
}

/// Collect an axum [`Response`](axum::response::Response) (respond-mode body or
/// an upstream-prep error) and write it to the downstream, appending `extra`
/// headers (e.g. the verified-payment receipt — respond-mode responses never
/// reach `response_filter`, so the receipt is attached here instead).
async fn write_axum_response(
    session: &mut Session,
    resp: axum::response::Response,
    extra: Vec<(HeaderName, HeaderValue)>,
) -> pingora::Result<()> {
    let _ = session.drain_request_body().await;
    let status = resp.status().as_u16();
    let headers: Vec<(String, String)> = resp
        .headers()
        .iter()
        .filter_map(|(n, v)| {
            v.to_str()
                .ok()
                .map(|v| (n.as_str().to_string(), v.to_string()))
        })
        .collect();
    let body = match axum::body::to_bytes(resp.into_body(), 16 * 1024 * 1024).await {
        Ok(b) => b,
        Err(e) => {
            tracing::warn!(error = %e, "write_axum_response: failed to read response body");
            Bytes::new()
        }
    };
    let mut out = ResponseHeader::build(status, None)?;
    for (n, v) in headers {
        if n.eq_ignore_ascii_case("content-length") {
            continue;
        }
        out.append_header(n, v)?;
    }
    // Receipt / settlement headers (HeaderValue passed through unchanged).
    for (n, v) in extra {
        let _ = out.append_header(n, v);
    }
    out.insert_header("content-length", body.len().to_string())?;
    session.write_response_header(Box::new(out), false).await?;
    session.write_response_body(Some(body), true).await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{
        buffered_upstream_headers, filtered_response_headers, is_control_plane,
        is_streamed_response,
    };
    use pay_core::server::gate::delegated_session_receipt_annotation;

    #[test]
    fn control_plane_paths_are_not_tracked() {
        // These bypass PDB tracking (request_filter) as well as payment.
        // The ephemeral skills poll must not surface as a failed request.
        for path in [
            "",
            "__402/health",
            "__402/pdb/api/config",
            "openapi.json",
            ".well-known/pay-skills.json",
        ] {
            assert!(is_control_plane(path), "{path} must be control-plane");
        }
        // Real upstream traffic still tracks.
        for path in ["v1/messages", "v1/chat/completions", "api/chat"] {
            assert!(!is_control_plane(path), "{path} must be tracked");
        }
    }

    #[test]
    fn buffered_upstream_headers_force_identity_encoding() {
        let headers = buffered_upstream_headers(&[
            ("accept-encoding".to_string(), "br, gzip".to_string()),
            ("content-type".to_string(), "application/json".to_string()),
        ]);

        assert_eq!(
            headers
                .iter()
                .filter(|(name, _)| name.eq_ignore_ascii_case("accept-encoding"))
                .count(),
            1
        );
        assert!(headers.iter().any(|(name, value)| {
            name.eq_ignore_ascii_case("accept-encoding") && value == "identity"
        }));
        assert!(headers.iter().any(|(name, value)| {
            name.eq_ignore_ascii_case("content-type") && value == "application/json"
        }));
    }

    #[test]
    fn filtered_response_headers_preserve_content_encoding() {
        let mut headers = reqwest::header::HeaderMap::new();
        headers.insert(
            reqwest::header::CONTENT_ENCODING,
            reqwest::header::HeaderValue::from_static("gzip"),
        );
        headers.insert(
            reqwest::header::CONTENT_LENGTH,
            reqwest::header::HeaderValue::from_static("123"),
        );
        headers.insert(
            reqwest::header::TRANSFER_ENCODING,
            reqwest::header::HeaderValue::from_static("chunked"),
        );

        let filtered = filtered_response_headers(&headers);

        assert_eq!(
            filtered
                .get(http::header::CONTENT_ENCODING)
                .and_then(|value| value.to_str().ok()),
            Some("gzip")
        );
        assert!(!filtered.contains_key(http::header::CONTENT_LENGTH));
        assert!(!filtered.contains_key(http::header::TRANSFER_ENCODING));
    }

    #[test]
    fn streamed_response_detection_accepts_sse_and_ndjson() {
        let mut sse = http::HeaderMap::new();
        sse.insert(
            http::header::CONTENT_TYPE,
            http::HeaderValue::from_static("text/event-stream; charset=utf-8"),
        );
        assert!(is_streamed_response(&sse));

        let mut ndjson = http::HeaderMap::new();
        ndjson.insert(
            http::header::CONTENT_TYPE,
            http::HeaderValue::from_static("application/x-ndjson"),
        );
        assert!(is_streamed_response(&ndjson));

        let mut json = http::HeaderMap::new();
        json.insert(
            http::header::CONTENT_TYPE,
            http::HeaderValue::from_static("application/json"),
        );
        assert!(!is_streamed_response(&json));
    }

    #[test]
    fn delegated_session_receipt_reports_the_accepted_voucher() {
        let annotation = delegated_session_receipt_annotation(
            "mainnet",
            pay_types::stablecoin_mints::USDC_MAINNET,
            "JAxsw27vxSNVSTEpgvnGPsGvfVmDX6jMqezbYU7D673Z",
            1,
            1,
            100_000,
        )
        .unwrap();
        let headers = annotation
            .headers
            .iter()
            .map(|(name, value)| {
                (
                    name.as_str().to_string(),
                    value.to_str().unwrap().to_string(),
                )
            })
            .collect::<Vec<_>>();
        let decoded = pay_core::client::receipt::decode_response_receipt(&headers).unwrap();

        assert_eq!(decoded.decoded["intent"], "session");
        assert_eq!(decoded.decoded["amount"], "1");
        assert_eq!(decoded.decoded["acceptedCumulative"], "1");
        assert_eq!(decoded.decoded["spent"], "1");
        assert_eq!(decoded.decoded["remaining"], "99999");
        assert!(headers.iter().any(|(name, value)| {
            name == "payment-receipt-url"
                && value == "https://pay.sh/receipt/JAxsw27vxSNVSTEpgvnGPsGvfVmDX6jMqezbYU7D673Z"
        }));
    }
}
